name: Deploy

on:
  workflow_dispatch
#  push:
#    branches:
#      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Setup key
      #  -e  Exit immediately if a command exits with a non-zero status.
      #  -u  Treat unset variables as an error when substituting.
      - run: |
              set -eu
              node -v
      - run: mkdir ~/.ssh
      - run: echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
      - run: chmod 600 ~/.ssh/key

      # Сформировать .env для сервера из секретов
      # DATABASE_HOST=11.11.1.1
      # DATABASE_USERNAME=user
      # DATABASE_PASSWORD=psw
          - name "Сформировать секреты"
          run |
            echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" > env.txt
            echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" > env.txt
            echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" > env.txt


      # Build
#      - run: npm ci
#      - run: npm run build
      # Deploy
#      поскольку пользователя удаленного компьютера также имеет смысл сделать рандомным - то я добавил секрет USER
      - run: rsync -e "ssh -i ~/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete ./config  "${{ secrets.USER }}@178.154.215.117:/var/www/gayrat.xyz/html/"
      - run: rsync -e "ssh -i ~/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete env.txt  "${{ secrets.USER }}@178.154.215.117:/var/www/gayrat.xyz/html/"

# для тестирования ключа попробуй войти на сервер по ssh с локального компьютера
#  ssh -i ~/.ssh22/id_rsa-private.txt root_user@178.154.215.117
