name: Deploy

on:
  workflow_dispatch
#  push:
#    branches:
#      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Setup key
      #  -e  Exit immediately if a command exits with a non-zero status.
      #  -u  Treat unset variables as an error when substituting.
      - run: |
              set -eu
              node -v
      - run: mkdir ~/.ssh
      - run: echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
      - run: chmod 600 ~/.ssh/key

      # Build
#      - run: npm ci
#      - run: npm run build
      # Deploy
#      - run: rsync -e "ssh -i ~/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete ./config xud3jc2@178.154.215.117:/var/www/gayrat.xyz/html/
      - run: rsync -e "ssh -i ~/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete ./config  "${{ secrets.USER }}@178.154.215.117:/var/www/gayrat.xyz/html/"


# работает!
# rsync -e "ssh -i ~/.ssh22/id_rsa-private.txt -o StrictHostKeyChecking=no" --archive --compress --delete ~/_prj/strapi/strapi-next-auth-deploy-to-vps/backend/app/config/ xud3jc2@178.154.215.117:/var/www/gayrat.xyz/html/

#  ssh -i ~/.ssh22/id_rsa-private.txt xud3jc2@178.154.215.117
